### ISSUE TITLE
[css-fonts] include WOFF 2.0 in font format (src descriptor) strings

### ISSUE THREAD

**Issue by kuettel** [litherum/csswg-drafts#4]
https://htmlpreview.github.io/?https://github.com/litherum/csswg-drafts/blob/variationfonts/css-fonts/Fonts.src.html#descdef-src

The format "woff2" should be included as an example, esp. as it is highly relevant in considering how best to support variation fonts.  

Currently proposed as "woff-variations" (which then would imply "woff2-variations"), could perhaps better captured as a parameter.  e.g. format("woff|woff2|ttf|otf", "variation")

**Comment by jfkthame** [comment]
The problem with `format("woff2", "variation")` (etc) is that if I understand correctly, this will not prevent the resource being used by browsers that don't support variation fonts. The current CSS Fonts spec[1] says:

> The format hint contains a comma-separated list of format strings that denote well-known font formats. Conformant user agents must skip downloading a font resource if the format hints indicate only unsupported or unknown font formats. If no format hints are supplied, the user agent should download the font resource.

which, at least as implemented in Firefox (I haven't tested this in other browsers) means that if *any* of the format strings indicates a supported format, the resource will be used.

I think what we want here is the opposite behavior, whereby if *any* of the format hints indicates an unsupported format or feature, the resource should be skipped. Then an author could say things like

    src: url("MyVarFont.woff2") format("woff2", "variation"),
           url("MyFont.woff2") format("woff2");

to provide a variation font to browsers that support it, and a non-variation one to legacy UAs. But that won't work in current Firefox; the first (variation) font will be used even though its "variation" format hint is not supported.

Maybe we can change this in the spec, and expect browsers to adjust as needed? I'm not aware that there has been any real use of multiple format hints at this point; it's not clear to me what current use-case would require them.

[1] https://www.w3.org/TR/css-fonts-3/#src-desc

**Comment by litherum** [comment]
The concept of variations are only applicable to certain font formats. Users should not be able to say format("svg", "variations").

**Comment by litherum** [comment]
Current browsers may interpret a two-argument format() function as a parse error, thereby disregarding the entire src descriptor, which is not what we want. We should do some research to know what happens in this case.

**Comment by litherum** [comment]
[Migrated](https://github.com/w3c/csswg-drafts/issues/513) to the official W3C repository, now that we resolved to pursue work there.
